# Generated by Django 4.0.4 on 2022-05-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.group'),
        ),
    ]
