<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-05-04 09:25
=======
# Generated by Django 4.0.4 on 2022-05-03 13:54
>>>>>>> be7d6bad8617bfb74a3fd71cb04da3be77098d17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant',
            new_name='name',
        ),
    ]
