# Generated by Django 4.0.4 on 2022-05-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant',
            new_name='name',
        ),
    ]
