# Generated by Django 4.0.4 on 2022-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
