# Generated by Django 4.0.4 on 2022-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_rank_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank_type',
            field=models.CharField(choices=[('CONFIRM', 'Confirm'), ('NORMAL', 'Normal')], default='NORMAL', max_length=15),
        ),
    ]
